# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rover_controller.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(330, 860)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.M1 = QtGui.QSlider(self.centralwidget)
        self.M1.setGeometry(QtCore.QRect(110, 100, 71, 22))
        self.M1.setOrientation(QtCore.Qt.Horizontal)
        self.M1.setObjectName(_fromUtf8("M1"))
        self.M2 = QtGui.QSlider(self.centralwidget)
        self.M2.setGeometry(QtCore.QRect(110, 150, 71, 22))
        self.M2.setOrientation(QtCore.Qt.Horizontal)
        self.M2.setObjectName(_fromUtf8("M2"))
        self.M3 = QtGui.QSlider(self.centralwidget)
        self.M3.setGeometry(QtCore.QRect(110, 200, 71, 22))
        self.M3.setOrientation(QtCore.Qt.Horizontal)
        self.M3.setObjectName(_fromUtf8("M3"))
        # self.M4 = QtGui.QSlider(self.centralwidget)
        # self.M4.setGeometry(QtCore.QRect(220, 100, 71, 22))
        # self.M4.setOrientation(QtCore.Qt.Horizontal)
        # self.M4.setObjectName(_fromUtf8("M4"))
        # self.M5 = QtGui.QSlider(self.centralwidget)
        # self.M5.setGeometry(QtCore.QRect(220, 150, 71, 22))
        # self.M5.setOrientation(QtCore.Qt.Horizontal)
        # self.M5.setObjectName(_fromUtf8("M5"))
        # self.M6 = QtGui.QSlider(self.centralwidget)
        # self.M6.setGeometry(QtCore.QRect(220, 200, 71, 22))
        # self.M6.setOrientation(QtCore.Qt.Horizontal)
        # self.M6.setObjectName(_fromUtf8("M6"))
        self.pushButton_m1f = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m1f.setGeometry(QtCore.QRect(10, 90, 21, 41))
        self.pushButton_m1f.setObjectName(_fromUtf8("pushButton_m1f"))
        self.pushButton_m1h = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m1h.setGeometry(QtCore.QRect(40, 90, 21, 41))
        self.pushButton_m1h.setObjectName(_fromUtf8("pushButton_m1h"))
        self.pushButton_m1n = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m1n.setGeometry(QtCore.QRect(70, 90, 21, 41))
        self.pushButton_m1n.setObjectName(_fromUtf8("pushButton_m1n"))
        self.pushButton_m2f = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m2f.setGeometry(QtCore.QRect(10, 140, 21, 41))
        self.pushButton_m2f.setObjectName(_fromUtf8("pushButton_m2f"))
        self.pushButton_m2h = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m2h.setGeometry(QtCore.QRect(40, 140, 21, 41))
        self.pushButton_m2h.setObjectName(_fromUtf8("pushButton_m2h"))
        self.pushButton_m2n = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m2n.setGeometry(QtCore.QRect(70, 140, 21, 41))
        self.pushButton_m2n.setObjectName(_fromUtf8("pushButton_m2n"))
        self.pushButton_m3f = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m3f.setGeometry(QtCore.QRect(10, 190, 21, 41))
        self.pushButton_m3f.setObjectName(_fromUtf8("pushButton_m3f"))
        self.pushButton_m3h = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m3h.setGeometry(QtCore.QRect(40, 190, 21, 41))
        self.pushButton_m3h.setObjectName(_fromUtf8("pushButton_m3h"))
        self.pushButton_m3n = QtGui.QPushButton(self.centralwidget)
        self.pushButton_m3n.setGeometry(QtCore.QRect(70, 190, 21, 41))
        self.pushButton_m3n.setObjectName(_fromUtf8("pushButton_m3n"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 15, 161, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.MotorPower = QtGui.QSlider(self.centralwidget)
        self.MotorPower.setGeometry(QtCore.QRect(30, 41, 271, 31))
        self.MotorPower.setOrientation(QtCore.Qt.Horizontal)
        self.MotorPower.setObjectName(_fromUtf8("MotorPower"))
        self.checkBox_motor = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_motor.setGeometry(QtCore.QRect(190, 70, 111, 20))
        self.checkBox_motor.setMinimumSize(QtCore.QSize(111, 20))
        self.checkBox_motor.setMaximumSize(QtCore.QSize(111, 16777215))
        self.checkBox_motor.setObjectName(_fromUtf8("checkBox_motor"))

        self.checkBox_motor1 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_motor1.setGeometry(QtCore.QRect(220, 100, 71, 22))
        self.checkBox_motor1.setMinimumSize(QtCore.QSize(111, 20))
        self.checkBox_motor1.setMaximumSize(QtCore.QSize(111, 16777215))
        self.checkBox_motor1.setObjectName(_fromUtf8("checkBox_motor1"))

        self.checkBox_motor2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_motor2.setGeometry(QtCore.QRect(220, 150, 71, 22))
        self.checkBox_motor2.setMinimumSize(QtCore.QSize(111, 20))
        self.checkBox_motor2.setMaximumSize(QtCore.QSize(111, 16777215))
        self.checkBox_motor2.setObjectName(_fromUtf8("checkBox_motor2"))

        self.checkBox_motor3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_motor3.setGeometry(QtCore.QRect(220, 200, 71, 22))
        self.checkBox_motor3.setMinimumSize(QtCore.QSize(111, 20))
        self.checkBox_motor3.setMaximumSize(QtCore.QSize(111, 16777215))
        self.checkBox_motor3.setObjectName(_fromUtf8("checkBox_motor3"))


        # self.graphicsView_X = QtGui.QGraphicsView(self.centralwidget)
        self.sceneX = QtGui.QGraphicsScene()
        self.graphicsView_X = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_X.setScene(self.sceneX)
        self.graphicsView_X.setGeometry(QtCore.QRect(20, 260, 141, 131))
        self.graphicsView_X.setObjectName(_fromUtf8("graphicsView_X"))

        # self.graphicsView_Y = QtGui.QGraphicsView(self.centralwidget)
        self.sceneY = QtGui.QGraphicsScene()
        self.graphicsView_Y = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_Y.setScene(self.sceneY)
        self.graphicsView_Y.setGeometry(QtCore.QRect(170, 260, 141, 131))
        self.graphicsView_Y.setObjectName(_fromUtf8("graphicsView_Y"))

        # self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        # self.scene = QtGui.QGraphicsScene()
        # self.graphicsView = QtGui.QGraphicsView(self.centralwidget)
        # self.graphicsView.setScene(self.scene)
        #
        # self.graphicsView.setGeometry(QtCore.QRect(325, 60, 900, 771))
        # self.graphicsView.setObjectName(_fromUtf8("graphicsView"))

        self.scene2 = QtGui.QGraphicsScene()
        self.graphicsView_2 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setScene(self.scene2)

        self.graphicsView_2.setGeometry(QtCore.QRect(20, 450, 291, 231))
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))

        self.lcd = QtGui.QLCDNumber(self.centralwidget)
        self.lcd.setGeometry(QtCore.QRect(200, 5, 61, 30))
        self.lcd.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(260, 120, 41, 20))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(150, 120, 41, 20))
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(260, 170, 41, 20))
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(150, 170, 41, 20))
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(260, 220, 41, 20))
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(150, 220, 41, 20))
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        # self.radioButton = QtGui.QRadioButton(self.centralwidget)
        # self.radioButton.setGeometry(QtCore.QRect(530, 30, 95, 20))
        # self.radioButton.setObjectName(_fromUtf8("radioButton"))
        # self.radioButton_2 = QtGui.QRadioButton(self.centralwidget)
        # self.radioButton_2.setGeometry(QtCore.QRect(620, 30, 95, 20))
        # self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        # self.radioButton_3 = QtGui.QRadioButton(self.centralwidget)
        # self.radioButton_3.setGeometry(QtCore.QRect(720, 30, 95, 20))
        # self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        # self.radioButton_4 = QtGui.QRadioButton(self.centralwidget)
        # self.radioButton_4.setGeometry(QtCore.QRect(820, 30, 95, 20))
        # self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.radioButton_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 420, 51, 20))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radioButton_5)
        self.radioButton_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(170, 420, 61, 20))
        self.radioButton_6.setObjectName(_fromUtf8("radioButton_6"))
        self.buttonGroup.addButton(self.radioButton_6)
        self.radioButton_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(90, 420, 61, 20))
        self.radioButton_7.setObjectName(_fromUtf8("radioButton_7"))
        self.buttonGroup.addButton(self.radioButton_7)
        self.radioButton_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(250, 420, 61, 20))
        self.radioButton_8.setObjectName(_fromUtf8("radioButton_8"))
        self.buttonGroup.addButton(self.radioButton_8)
        self.textBrowser = QtGui.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 700, 291, 131))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_m1f.setText(_translate("MainWindow", "F", None))
        self.pushButton_m1h.setText(_translate("MainWindow", "H", None))
        self.pushButton_m1n.setText(_translate("MainWindow", "N", None))
        self.pushButton_m2f.setText(_translate("MainWindow", "F", None))
        self.pushButton_m2h.setText(_translate("MainWindow", "H", None))
        self.pushButton_m2n.setText(_translate("MainWindow", "N", None))
        self.pushButton_m3f.setText(_translate("MainWindow", "F", None))
        self.pushButton_m3h.setText(_translate("MainWindow", "H", None))
        self.pushButton_m3n.setText(_translate("MainWindow", "N", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Motors Power Control:</span></p></body></html>", None))
        self.checkBox_motor.setText(_translate("MainWindow", "For move only", None))
        # self.radioButton.setText(_translate("MainWindow", "Map", None))
        # self.radioButton_2.setText(_translate("MainWindow", "Camera 0", None))
        # self.radioButton_3.setText(_translate("MainWindow", "Camera 1", None))
        # self.radioButton_4.setText(_translate("MainWindow", "Camera 2", None))
        self.radioButton_5.setText(_translate("MainWindow", "Map", None))
        self.radioButton_6.setText(_translate("MainWindow", "Cam 1", None))
        self.radioButton_7.setText(_translate("MainWindow", "Cam 0", None))
        self.radioButton_8.setText(_translate("MainWindow", "Cam 2", None))

